
services:
  auth-service:
    build:
      context: ./authservice
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mploki78)P
      - MYSQL_DATABASE=clientsatisfaction
  ticket-service:
    build:
      context: ./ticketservice
    ports:
      - "8082:8080"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mploki78)P
      - MYSQL_DATABASE=clientsatisfaction
