apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clientsupport-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: clientsupport.local
    http:
      paths:
      - path: /authservice
        pathType: Prefix
        backend:
          service:
            name: authservice  
            port:
              number: 8080
      - path: /ticketservice
        pathType: Prefix
        backend:
          service:
            name: ticketservice 
            port:
              number: 8080
