apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  type : NodePort
  ports:
    - name: http
      targetPort: 8080
      port: 80
      nodePort: 30001
  selector:
    app: authservice
