apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: ouarda658/clientsupport-auth-service:v1
          env:
            - name: MYSQL_HOST
              value: "mysql"  
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "clientsatisfaction"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mploki78)P"