
FROM openjdk:21-jdk-slim


WORKDIR /app

COPY build/libs/ticketservice-0.0.1-SNAPSHOT.jar ticketservice.jar
COPY src/main/resources/application.properties /app/resources/

EXPOSE 8080


ENTRYPOINT ["java", "-jar", "ticketservice.jar"]
