apiVersion: v1
kind: Service
metadata:
  name: ticketservice
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 8080
      port: 80
      nodePort: 30002
  selector:
    app: ticketservice