apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketservice
  template:
    metadata:
      labels:
        app: ticketservice
    spec:
      containers:
        - name: ticketservice
          image: ouarda658/ticketservice-clientsupport:final1
          env:
            - name: MYSQL_HOST
              value: "mysql"  
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "clientsatisfaction"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mploki78)P"
            - name: GRPC_CLIENT_SENTIMENTSERVICE_ADDRESS
              value: "static://sentimentservice:9090"
            - name: GRPC_CLIENT_SENTIMENTSERVICE_NEGOTIATIONTYPE
              value: "PLAINTEXT"